{{- if .Values.openshift.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "agile-retro.fullname" . }}
  labels:
    {{- include "agile-retro.labels" . | nindent 4 }}
spec:
  host: {{ .Values.openshift.route.host }}
  to:
    kind: Service
    name: {{ include "agile-retro.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
